# Generated by Django 3.1.3 on 2020-11-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True)),
                ('created', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ManyToManyField(to='authors.Author')),
            ],
        ),
    ]
